### ISSUE TITLE
top level keys for jinja2 yaml file

### ISSUE THREAD

**Issue by openprivacy** [CivicActions/secrender#2]
Capturing @woodt notes from a side conversation:

> We could change secrender to create Jinja2 variables for every top-level key in the YAML file, and get rid of the root variable idea.  The -r option could hang around as a way of renaming variables as opposed to a way to specify the root variable.

Then we could reference `{{contractor.name_short}}` from a file like:
```
project:
  name_short: Example Project

contractor:
  name_short: Example
  support_email: support@example.com
```
